config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root to: 'pages#home'
  get 'accommodation',       to: 'pages#accommodation', as: 'accommodation'
  get 'contact_us',       to: 'pages#contact_us', as: 'contact_us'
  get 'gallery',       to: 'pages#gallery', as: 'gallery'
  get 'rooms_list',       to: 'pages#rooms_list', as: 'rooms_list'
  get 'restaurant',       to: 'pages#restaurant', as: 'restaurant'

  # get 'pages/calculator'
  # get 'calculator' => 'pages#calculator'
  # post 'pages/calculator'

  match "calculator" => "pages#calculator", :via => [:post, :get]

  resources :rooms, only: [:index, :show]
  resources :contacts, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :check_in_date, :check_out_date, :adult_guest, :children_guest , presence: true

  ADULT_GUESTS = [["1 Adult", 1],  ["2 Adults", 2], ["3 Adults", 3], ["4 Adults", 4]]
  CHILDREN_GUESTS = [["0 Children", 0], ["1 Child", 1], ["2 Children", 2], ["3 Children", 3], ["4 Children", 4]]
end

def guests
	adult_guest + children_guest
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :first_name, :validate => true
	attribute :last_name, :validate => true
	attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :subject
	attribute :message, :validate => true
	attribute :nickname, :captcha => true

	def headers 
		{
			:subject => "Contact Form",
			:to => "m3restaurant.barlounge@gmail.com",
			:from => %("#{first_name.capitalize} #{last_name.capitalize}" <#{email}>)
		}
	end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	validates :name, presence: true, uniqueness: true	
	has_many :bookings
	has_many :room_attachments
	accepts_nested_attributes_for :room_attachments
	# has_many :photos, through: :room_attachmens

	COORDINATES = [{
	     lat:  -25.056682,
	     lng: 33.664984
  	}]

	def self.search(search)
	  where(available: true) 
	end

	def photos
	    RoomAttachment.where(room: self)
	end
end

app/models/room_attachment.rb
class RoomAttachment < ApplicationRecord
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]

 





end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	skip_before_action :authenticate_user!, only: [:new, :create]



	def new
		@contact = Contact.new
		@markers = Room::COORDINATES
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message'
			render :new
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :accommodation, :calculator, :contact_us, :gallery, :rooms_list, :restaurant]

  def home
  	@rooms = Room.all
  end

  def accommodation
    @room = Room.new
  	@rooms = Room.all
    @booking = Booking.new
  end

  def contact_us

   # @coordinates = Room::COORDINATES
   @markers = Room::COORDINATES
     
  
  

    # @markers = {lat: 38.720122, lng: -9.1666243,17}
    # function initMap() {
    #   var myLatLng = {lat: -25.363, lng: 131.044};

    #   var map = new google.maps.Map(document.getElementById('map'), {
    #     zoom: 4,
    #     center: myLatLng
    #   });

    #   var marker = new google.maps.Marker({
    #     position: myLatLng,
    #     map: map,
    #     title: 'Hello World!'
    #   });
    # }
  end

  def gallery
  end

  def restaurant
  end


  def rooms_list
    @rooms = Room.all
  end


  def calculator
  	
	  	@name1 = params[:name]
	  	if @name1 == ""
	  		@error_msg = "must enter your name!"
	  	end
	  	@email1 = params[:email]
	  	@product1 = params[:product1]
	  	@question = params[:question]
	  	@newsleter = params["newslater"] == "newsleter"
	  	gender = params[:gender]
	  	@male = gender == "male"
	  	@female = gender == "female"
	  	# form tag variables
	  	@name = params["Name"]
  		@email  = params[:email]
  		@age = params[:age]
  		@products = %w(Skiis Poles Mittens)
  		@selected_product = params[:product]
  		@salad = params[:food] == "salad"
  		@main = params[:food] == "main"
  		@desert = params[:food] == "desert"
  	
  	
  		



  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  	skip_before_action :authenticate_user!, only: [:index, :show]

  	def index

  		# @rooms = Room.all
  		@booking = Booking.new
  		# pry-byebug
  		 @bookings_params  = request.query_parameters[:booking]
       @check_in_date = @bookings_params[:check_in_date]
       @check_out_date = @bookings_params[:check_out_date]
       @adult_guest = @bookings_params[:adult_guest]
       @children_guest = @bookings_params[:children_guest]


       if @check_in_date.present? 
         @check_in_date = Date.parse(@bookings_params[:check_in_date]) 
          # @check_out_date = Date.parse(@bookings_params[:check_out_date]) 
       else
         # @check_in_date = Date.today.strftime("%Y.%m.%d")
         @check_in_date = Date.today
         # @check_out_date = @check_in_date + 1
       end

        if @check_out_date.present?
          @check_out_date = Date.parse(@bookings_params[:check_out_date]) 
        else
          @check_out_date = @check_in_date + 1 
        end
        
   		  # if @dult_guest.present? || @children_guest.present?
       #     @adult_guest = @bookings_params[:adult_guest]
       #     @children_guest = @bookings_params[:children_guest]
       #  else
       #    @adult_guest = 1
       #    @children_guest = 0
       #  end
       
        @nights = (@check_out_date - @check_in_date).to_i 
        @bookings_params = { "check_in_date" => @check_in_date, "check_out_date" => @check_out_date, "adult_guest" => @adult_guest, "children_guest" => @children_guest}
        session[:passed_variable] = @bookings_params


        

   		if params[:commit]
   		    @rooms = Room.search(params[:search]).order("created_at DESC")
   		else
   		    @rooms = Room.all.order('created_at DESC')
   		end

  	end

  	def show

     @new_params = session[:passed_variable] 
     @check_in_date = Date.parse(@new_params["check_in_date"])
     @check_out_date = Date.parse(@new_params["check_out_date"])
     @adult_guest = @new_params["adult_guest"]
     @children_guest = @new_params["children_guest"]
     # raise
      if @check_in_date.present?
        @check_in_date = Date.parse(@new_params["check_in_date"])
      else
         @check_in_date = Date.today
      end

      if @check_out_date.present?
        @check_out_date = Date.parse(@new_params["check_out_date"])
      else
        @check_out_date = @check_in_date + 1 
      end

      if @dult_guest.present? || @children_guest.present?
       @adult_guest = @new_params["adult_guest"]
         @children_guest = @new_params["children_guest"]
      else
        @adult_guest = 1
        @children_guest = 0
      end

     @nights = (@check_out_date - @check_in_date).to_i  

     

      @booking = Booking.new
  		@room = Room.find(params[:id])
      @room_attachments = @room.room_attachments.all
      @more_rooms = Room.where(available: true).where.not(id: @room.id)
     
     
  	end

end
 

app/helpers/application_helper.rb
module ApplicationHelper

	def ellipsis(text, limit, default='…')
	  text[0..limit].gsub(/\s\w+\s*$/, default)
	end
end

app/views/contacts/create.html.erb
<div class="lg-upper-page-banner thank-you-page-banner">
</div>
<div class="wrapper-thank-you-message">
	<div class="container">
		<div class="message-container">
			<div class="message-description">
				<div class="icon">
					<i class="far fa-check-circle"></i>
				</div>
				<h1>Thank you!  </h1>
				<p>Thank your for getting in touch! <br>Your message has been sent and we will get back to you shortly! </p>
			</div>
		</div>
	</div>
</div>

app/views/contacts/text.html.erb
<div class="lg-upper-page-banner">
	<div class="banner-content">
		<h1>hey there</h1>

	</div>
</div>
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<%= form_for @contact do |f| %>
			<%= f.label :name %> <br>
			<%= f.text_field :name, required: true %>

			<br>

			<%= f.label :email %> <br>
			<%= f.email_field :email, required: true %>

			<br>

			<%= f.label :message %> <br>
			<%= f.text_area :message, required: true %>

			<div class="hidden">
				<%= f.label :nickname %> <br>
				<%= f.text_field :nickname, hint: 'leave this field blank' %>
			</div>

			<br>

			<%= f.submit 'Send Message', class: " btn button" %>
		<% end %>
	</div>

	
	

		</p>
</div>

app/views/pages/home.html.erb
<div class="banner">
	
	<div class="heading-primary">
		<h1 class="heading-primary--main"><span class="title-bold">WELCOME TO</span> <span class="title-light">M3 VILLAGE</span></h1>
		<h3 class="heading-primary--sub">XAI-XAI | MOZAMBIQUE</h3>
		<%= link_to "ACCOMMODATION",  accommodation_path, class: "btn-banner " %>
		<%= link_to "RESTAURANT & BAR", restaurant_path, class: "btn-banner " %>
	</div>
</div>

<div class="wrapper-aboutus" id="section-about-us">
	<div class="container">
		<h4>About us</h4>
		<hr>
		<p>
			M3 Village Xai-Xai provides accommodation, restaurant and bar services in Xai-Xai.

			We are located in Gaza Province, Xai-Xai district(capital), with easy access to pretty much anywhere in the region. We're around 210 km away from Maputo Capital and 250Km from Inhambane Province. <br>
			We are just a few minutes away from major medical facilities, supermarkets, bancs and petrol stations. 


			Thanks to our strategic location, you will be able to save time during your stay and optimize your rest. In this way, you will benefit from a perfect combination of time, pleasure and relaxation. <br> <br>

			Xai-Xai beach is located around 10 km from the property, where boat lunche's, fishing and diving activities take place. Other beachs nearby can be visited such Bilene, Zongoene and Chibuto. <br> <br>
		 
		
			At the guest house, the rooms are equipped with a private bathroom, air conditioning and a flat-screen TV. 
			<br>
			We also have a restaurant that offers a wide variety of seafood dishes, and you can also taste delicious Mozambican typical food, as dishes of International cuisines. <br>
			Our Bar provides you relaxed moments while having some drinks. In the weekends, you can have fun in the bar that provides you with live music nights.

			Both free WiFi and private parking are available on site. <br>
		 </p>	

	</div>

</div>
<div class="wapper-paralax about-you-parallax-banner">
	<div class="header-background">
		<h1>It's all about You!</h1>
	</div>
</div>
<div class="wrapper-aboutus">
	<div class="container">
		<h4>We care about you.</h4>
		<hr>
		<p>We know you travel for all kinds of reasons: for work, for fun and sometimes for both. No matter what brings you to us, you will always get our best. Our lovely staff, free high-speed internet, and good service make business effortless. But there is something about our hotel that will make you want to unwind and take some time for yourself. Maybe it is our great bar & restaurant, or our modern and cozy rooms, or simply our inviting beds for a good rest. Work and leisure have hardly mixed this well.
		 </p>	

	</div>

</div>
<div class="wapper-paralax rooms-paralax-banner">
	<div class="header-background">
		<h1>Explore our rooms.</h1>
	</div>
</div>
<div class="wrapper-rooms">
	<div class="container">
		<h4>Rooms</h4>
		<p>We'll provide you with clean, confortable and well equiped rooms, that 
			match your needs!
			With a great night’s sleep, and a hot, powerful shower, we have everything you need to get out there rested, refreshed and ready for the day. Our afro-chic modern infrastructure offers 6 rooms with private bathroom, air conditioning, a LED flat screen TV, a minibar and a separate seating area. We have: <br>
			• 4 executive sweet rooms with queen size beds <br>
			• 1 double room with with a queen size bed <br>
			• 1 double room with 2 single beds <br>

			Our guests are also offered a delicious breakfast to help kickstart the day in good shape and mood.
		</p>
		<div class="row">
			<% @rooms.each do |r| %>
			<div class="col-xs-12 col-sm-6">
				<%= render  "rooms/room", room: r %>
			</div>
			<% end %>	
		</div>
	</div>
	<div class="cta-rooms">
		<%= render 'shared/btn-book' %>	
	</div>
	
</div>
<div class="wapper-paralax food-drinks-paralax-banner">
	<div class="header-background">
		<h1>Food & Drinks.</h1>
	</div>
</div>
<div class="wrapper-foodrinks">
	<div class="container">
		<h4>Food & Drinks</h4>
		<!-- <p>Enjoy a broad selection of dishes representative of Mozambican and International cuisines, all carefully prepared by our chef</p> -->	
		<p>Good things happen around good food and drink, because we take the time to get to know each other and put life back into perspective. <br>We make it easy to do that by providing a restaurant & bar that are inviting enough to make you want to unwind and share the stories of the day. Enjoy a broad selection of dishes representative of Mozambican and International cuisines, all carefully prepared by our chef, or just grab a signature cocktail, or a beer and chill.</p>
		<div class="row">			
				<div class="col-xs-12 col-sm-6 col-md-4">
					<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'stake.jpg' %>);">
					</div>
				</div>	
				<div class="col-xs-12 col-sm-6 col-md-4">
					<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'seafood.jpg' %>);">
					</div>					
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4">
					<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'crepe.jpg' %>);">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4">
					<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'tiramisu.jpg' %>);">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4">
					<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'pizza.jpg' %>);">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4">
					<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'burger.jpg' %>);">
					</div>					
				</div>					
		</div>	
	</div>
	<div class="foodrinks-button">
		<%= render 'shared/btn-foodrinks' %>
	</div>
</div>

<div class="wrapper-reviews">
	<div class="container">
		<div class="banner-reviews">
			<div class="container">
				<h4>Reviews</h4>
				<div class="review-box">
					<div class="reviews-content">
						<%= image_tag "laura.jpg", class: "avatar-lg" %>
						<p>The Guesthouse stay was very pleasant and comfortable. The staff was very polite and helpful, the location was very convenient for getting around and many activities. If we were to travel to Xai-Xai again, we would definitely stay there again!</p>				
					</div>
					<div class="rewiew-user">
						<p class="review-username">Laura Johnson &nbsp;&nbsp;-</p><p class="review-date">September 2018</p>		
					</div>		
				</div>		 			
			</div>
		</div>
		<div class="link-reviews">
			<%= link_to "view more reviews", "#" %>
		</div>
		
	</div>

</div>


<div class="wrapper-otherservices">
	<div class="container">
		<h4>Other Services</h4>

		<hr>
		<div class="row">
			<div class="col-xs-6">
				<div class="card-pub-content">
					<h5>Bar</h5>
					<p><span class="card-pub-description">At the end of the day, we allow you to relax and take some drinks.
					Just grab a signature cocktail, or a beer and chill.
					The bar also welcomes people who want a glass of champagne or have an aperitif with friends to relax after a busy day.
				</span></p>	
				</div>
				
			</div>
			<div class="col-xs-6">
				<div class="card-pub" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'cocktail.jpg' %>);">
				</div>	
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-xs-6">
				<div class="card-pub-content">
					<h5>Live Music</h5>
					<p><span class="card-pub-description"> 
					We provide you with a relaxed atmosphere on the weekends with good music and nice drinks. Join us on the weekends and enjoy our warm live music evenings hosted by great singers.
					</span></p>	
				</div>
				
			</div>
			<div class="col-xs-6">
				<div class="card-pub" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= asset_path'live-music.jpg' %>);">
				</div>
				
			</div>
		</div>
		
	</div>

	<br>
	<br>

</div>

app/views/shared/_btn-book-now.html.erb
<%= link_to "BOOK NOW", new_contact_path(:anchor => "Contact-us-form"), class: "btn-book-now" %>

app/views/shared/_btn-book.html.erb
<%= link_to "BOOK", new_contact_path(:anchor => "Contact-us-form"), class: "btn-book cta-book-footer" %>

app/views/shared/_btn-foodrinks.html.erb
<%= link_to "view gallery", gallery_path, class: "btn-restaurant " %>

app/views/shared/_btn-search.html.erb
<%= link_to "SEARCH", "#", class: "btn-search btn-search-results" %>

app/views/shared/_footer.html.erb
<footer class="wrapper-footer">
	<div class="container-fluid">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-4">
					<div class="address-section">
						<%= link_to root_path, class: "logo-footer" do %>
							<%= image_tag "logo.png", height: 50 %>
						<% end %>
						<span class= "logo-name"><p>M3 VILLAGE</p></span>
						<span class="contact-txt"><p>Do you have any questions?<br>Feel free to contact us</p></span>
						<span class="footer-adress"><p>Rua do M3<br> Xai-Xai - Mozambique <br>m3restaurant.barlounge@gmail.com<br>+258 84 619 2578</p></span>
					</div>
				</div>
				<div class="col-xs-12 col-sm-4">
					<div class="links-section1">
						<p><%= link_to "About us", root_path( :anchor => "section-about-us") %></p>
						<p><%= link_to "Contact",  new_contact_path %> </p>
						<p><%= link_to "Gallery",  gallery_path %></p>
						<span class="visit-us-txt hidden-xs"><p>Come and visit us <br>Check for rooms availability</p></span>
					</div>
					
				</div>
				<div class="col-xs-12 col-sm-4">
					<div class="links-section2">
						<p><%= link_to "Restaurant & Bar", restaurant_path %></p>
						<p><%= link_to "Accomodation", accommodation_path %></p>
						<p> <%= link_to "Rooms", rooms_list_path  %></p>
						<span class="hidden-xs"><%= render 'shared/btn-book'  %></span>	
					</div>
				</div>
			</div>
			<div class="rights-reserved">
				<small>Copyright © M3Village 2018. All Rights Reserved.</small>
			</div>
		</div>
	</div>	
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-wagon">
  <!-- Logo -->
      <%= link_to root_path, class: "navbar-wagon-brand navbar-wagon-right hidden-md hidden-lg" do %>
        <%= image_tag "logo.png", height: 50 %>
      <% end %>
      <p><span class= "hidden-xs hidden-sm">Rua do M3, Xai-Xai |m3restaurant.barlounge@gmail.com</span></p>

  <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%# if user_signed_in? %>

      <!-- Links when logged in -->
        
        <%= link_to "https://www.facebook.com/M3-Village-1431699646956731/", class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fab fa-facebook-square facebook"></i> 
        <% end %> 
        <%= link_to "EN", "#", class: "active nav-icons navbar-wagon-link" %>|<%= link_to "PT", "#", class: "language-pt navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <!-- <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div> -->
    <%# else %>
      <!-- Login link (when logged out) -->
      <%#= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
       <!--  <i class="fab fa-facebook-square facebook"></i>  -->
      <%# end %> 
<!--       <%#= link_to "EN", "#", class: "active nav-icons navbar-wagon-link" %>|<%#= link_to "PT", "#", class: "language-pt navbar-wagon-link" %>
 -->      <%#= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%# end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown-flex">
      <div class="language">
        <%= link_to "EN", "#", class: "active nav-icons navbar-wagon-link" %>|<%= link_to "PT", "#", class: "language-pt navbar-wagon-link" %>
      </div>
      
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "About us", root_path( :anchor => "section-about-us"), class: "navbar-item-left avbar-wagon-item navbar-wagon-link"  %></li>
          <li><%= link_to "Rooms", rooms_list_path, class: "avbar-wagon-item navbar-wagon-link"  %></li>
          <li><%= link_to "Gallery",  gallery_path, class: "avbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Accommodation", accommodation_path, class: "avbar-wagon-item navbar-wagon-link"  %></li> 
          <li><%= link_to "Restaurant&Bar", restaurant_path, class: "avbar-wagon-item navbar-wagon-link"  %> </li>
          <li><%= link_to "Contact",  new_contact_path ,class: "navbar-item-right avbar-wagon-item navbar-wagon-link"  %></li>
        </ul>
    </div>
    </div>
    
  </div>
  <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown-flex">
      <div class="language">
        <%#= link_to "EN", "#", class: "active nav-icons navbar-wagon-link" %>|<%#= link_to "PT", "#", class: "language-pt navbar-wagon-link" %>
      </div>
      
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%#= link_to "About us", root_path( :anchor => "section-about-us"), class: "navbar-item-left avbar-wagon-item navbar-wagon-link"  %></li>
          <li><%#= link_to "Rooms", rooms_list_path, class: "avbar-wagon-item navbar-wagon-link"  %></li>
          <li><%#= link_to "Gallery",  gallery_path, class: "avbar-wagon-item navbar-wagon-link" %></li>
          <li><%#= link_to "Accommodation", accommodation_path, class: "avbar-wagon-item navbar-wagon-link"  %></li> 
          <li><%#= link_to "Restaurant&Pub", restaurant_path, class: "avbar-wagon-item navbar-wagon-link"  %> </li>
          <li><%#= link_to "Contact",  new_contact_path ,class: "navbar-item-right avbar-wagon-item navbar-wagon-link"  %></li>
        <%# if user_signed_in? %>
      <li><%#= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%#= t(".sign_out", default: "Log out") %>
            <%# end %>
          </li>
        <%# else %>          
        <li><%#= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%# end %>   
      </li>
      </ul>
    </div>
    </div>
    
  </div> -->
</div>


  <div class="navbar-large hidden-xs hidden-sm">
    <div class="container">
      <div class="navbar-links hidden-xs hidden-sm">

        <%= link_to "Accommodation", accommodation_path, class: "avbar-wagon-item navbar-wagon-link"  %>
        
          <%= link_to "About us", root_path( :anchor => "section-about-us"), class: "navbar-item-left avbar-wagon-item navbar-wagon-link"  %>
          <%= link_to "Rooms", rooms_list_path, class: "avbar-wagon-item navbar-wagon-link"  %>
          

          
           <%= link_to root_path, class: "logo" do %>
              <%= image_tag "logo.png", height: 60 %>
            <% end %>
      
          <%= link_to "Gallery",  gallery_path, class: "avbar-wagon-item navbar-wagon-link" %>

          <%= link_to "Contact",  new_contact_path ,class: "navbar-item-right avbar-wagon-item navbar-wagon-link"  %> 
          <%= link_to "Restaurant&Bar", restaurant_path, class: "avbar-wagon-item navbar-wagon-link"  %>          
      </div>    
    </div>    
  </div>  
</div>
 

<!-- <div class="navbar-mini hidden-xs hidden-sm">
    <div class="container">
      <div class="nav-flexbox">
        <p>Rua do Miau Miau, Xai-Xai |hello@m3village.com</p>
        <div class="nav-icons">          
          <%= link_to "EN", "#", class: "active" %>|<%= link_to "PT", "#" %>
        
          <%= link_to "#" do %>
              <i class="fab fa-facebook-square"></i> 
          <% end %> 
          <%= link_to "Login", "#" %>
        </div>
      </div>
    </div>
  </div>
 -->
  